import { defineStore } from 'pinia'
import offerImg from '@/assets/images/offerImg.png'
import best from '@/assets/images/best.png'
import { useApi } from '@/composables/useApi'
import { NewArrivalProducts, ProductsResponse } from '@/types/Interfaces/products'

export const useProductsStore = defineStore('products', {
  state: () => ({
    products: {} as ProductsResponse,
    productOffer: [
      {
        title: 'Enhance Your Music Experience',
        productName: 'JBL Boombox 3',
        imageUrl: offerImg,
        slug: '/product/boombox-3',
        expiresAt: '2025-06-10T23:59:59Z',
      },
    ],
    newArrivalProducts: [] as NewArrivalProducts[],
    exploreProducts: [
      {
        id: 1,
        title: 'The north coat',
        image: best,
        price: 260,
        oldPrice: 360,
        discount: 28,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 2,
        title: 'Gucci duffle bag',
        image: best,
        price: 960,
        oldPrice: 1160,
        discount: 17,
        rating: 4.5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 3,
        title: 'RGB liquid CPU Cooler',
        image: best,
        price: 160,
        oldPrice: 170,
        discount: 6,
        rating: 4.5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 4,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 5,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 6,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 7,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 8,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 9,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 10,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 11,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 12,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 13,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 14,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 15,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 16,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
    ],
    bestSellingProducts: [
      {
        id: 1,
        title: 'The nаorth coat',
        image: best,
        price: 260,
        oldPrice: 360,
        discount: 28,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 2,
        title: 'Gucci duffle bag',
        image: best,
        price: 960,
        oldPrice: 1160,
        discount: 17,
        rating: 4.5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 3,
        title: 'RGB liquid CPU Cooler',
        image: best,
        price: 160,
        oldPrice: 170,
        discount: 6,
        rating: 4.5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 4,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
    ],
  }),

  actions: {
    async getProducts(limit: number, page: number) {
      const { api } = useApi()
      const res = await api.get('/product/discounts', {
        limit,
        page,
      })

      this.products = res
    },

    async getNewArrivalProducts() {
      const { api } = useApi()
      this.newArrivalProducts = await api.get('/product/new-arrivals')
    },
  },
})
