import { defineStore } from 'pinia'
import offerImg from '@/assets/images/offerImg.png'
import best from '@/assets/images/best.png'
import padMini from '@/assets/images/gamepad-mini.png'
import padMini2 from '@/assets/images/padMini-2.png'
import padBig from '@/assets/images/gamepad-big.png'
import { useApi } from '@/composables/useApi'
import { NewArrivalProducts, ProductsResponse, ProductDetails } from '@/types/Interfaces/products'

const { api } = useApi()

export const useProductsStore = defineStore('products', {
  state: () => ({
    products: {} as ProductsResponse,
    productOffer: [
      {
        title: 'Enhance Your Music Experience',
        productName: 'JBL Boombox 3',
        imageUrl: offerImg,
        slug: '/product/boombox-3',
        expiresAt: '2025-06-10T23:59:59Z',
      },
    ],
    newArrivalProducts: [] as NewArrivalProducts[],
    exploreProducts: [
      {
        id: 1,
        title: 'The north coat',
        image: best,
        price: 260,
        oldPrice: 360,
        discount: 28,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 2,
        title: 'Gucci duffle bag',
        image: best,
        price: 960,
        oldPrice: 1160,
        discount: 17,
        rating: 4.5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 3,
        title: 'RGB liquid CPU Cooler',
        image: best,
        price: 160,
        oldPrice: 170,
        discount: 6,
        rating: 4.5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 4,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 5,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 6,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 7,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 8,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 9,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 10,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 11,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 12,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 13,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 14,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 15,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 16,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
    ],
    bestSellingProducts: [
      {
        id: 1,
        title: 'The nаorth coat',
        image: best,
        price: 260,
        oldPrice: 360,
        discount: 28,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 2,
        title: 'Gucci duffle bag',
        image: best,
        price: 960,
        oldPrice: 1160,
        discount: 17,
        rating: 4.5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 3,
        title: 'RGB liquid CPU Cooler',
        image: best,
        price: 160,
        oldPrice: 170,
        discount: 6,
        rating: 4.5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
      {
        id: 4,
        title: 'Small BookSelf',
        image: best,
        price: 360,
        oldPrice: null,
        discount: 0,
        rating: 5,
        reviewsCount: 65,
        isFavorite: false,
        isViewed: false,
        currency: '$',
      },
    ],
    cardProduct: [
      {
        id: 1,
        image: padBig,
        thumb: padMini,
      },
      {
        id: 2,
        image: padBig,
        thumb: padMini,
      },
      {
        id: 3,
        image: padBig,
        thumb: padMini2,
      },
      {
        id: 4,
        image: best,
        thumb: best,
      },
    ],
    cardProductDetails: {} as ProductDetails,
  }),

  actions: {
    async getDiscountProducts(limit: number, page: number) {
      this.products = await api.get('/product/discounts', {
        limit,
        page,
      })
    },

    async getNewArrivalProducts() {
      this.newArrivalProducts = await api.get('/product/new-arrivals')
    },

    setProductDetails(details: ProductDetails) {
      this.cardProductDetails = details
    },

    async getProductDetails(slug: string) {
      if (!this.cardProductDetails.id) {
        this.cardProductDetails = await api.get(`/product/${slug}`)
      }
    },
  },
})
